✨ Criar modelo de ProjectFiscal
common-group/services-core pull request #1005
Opened 2021-07-29 17:34 UTC by gabrielras

### Descrição
Criação do modelo e da action de criação para Project Fiscals.

### Referência
https://www.notion.so/catarse/Criar-estrutura-para-gerar-dados-fiscais-de-projetos-ddf98e00ef9540c9807cf80a24b9f2aa

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-08-02 17:39 UTC, leticia-fernandes commented on services/catarse/app/models/project_fiscal.rb
> +  monetize :total_amount_cents, numericality: { greater_than_or_equal_to: 1 }
**Curiosidade:** Pq o uso do sufixo `_cents` ? :thinking:

2021-08-02 17:41 UTC, leticia-fernandes commented on services/catarse/app/old_actions/create_nfe_to_project_flex_and_aon_action.rb
> +  def total_geteway_fee(state)
**Dúvida:** Tá correto o nome `geteway` mesmo? Ou deveria ser `gateway` ?

2021-08-02 17:43 UTC, leticia-fernandes approved these changes

2021-08-02 18:48 UTC, stephannv requested changes
Tenho que revisar esse PR aqui com mais calma. Talvez eu faça um code review em par, pois acho que tem algumas coisas que precisam ser projetadas de uma maneira diferente.

2021-08-02 18:51 UTC, stephannv commented on services/catarse/app/models/project_fiscal.rb
> +  monetize :total_amount_cents, numericality: { greater_than_or_equal_to: 1 }
@leticia-fernandes é por conta da nova gem que a gente usa, que armazena os valores em centavos e não mais em números decimais, daí pra não ficar nenhuma ambiguidade ou dúvida, o `_cents` deixa claro o que a coluna representa, mas no modelo, teremos a facilidade de usar `total_amount` que retorna um objeto do tipo Money, e daí a gente pode chamar um `format`, um `cents`, um `to_f`, dependendo da situação.

2021-08-03 19:01 UTC, stephannv requested changes

2021-08-05 12:54 UTC, gabrielras commented on services/catarse/lib/e_notas/query.rb
> +module ENotas
Foi removido

2021-08-09 18:35 UTC, stephannv approved these changes

2021-08-10 17:44 UTC, devton approved these changes

2021-08-10 18:02 UTC, merged