🐞 Remove aba 'Assinantes' de projetos de assinatura
common-group/services-core pull request #1036
Opened 2021-08-12 17:08 UTC by leticia-fernandes

### Descrição
Essa alteração remove a aba 'Assinantes', já que não está carregando as informações. O código não foi removido, pois ainda será decidido o que será feito em definitivo.

### Referência
https://www.notion.so/catarse/LGPD-Remover-aba-de-Assinantes-de-projetos-de-Assinatura-e723a4d146fc4e8581c10abd36ad559c

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [X] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [X] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [X] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-08-16 14:24 UTC, stephannv approved these changes

2021-08-16 14:34 UTC, stephannv requested changes

2021-08-16 14:34 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/project-tabs.js
> +                            : '',
**Sugestão**
Pelo que percebi a aba não foi removida, só foi escondida mas no código continua lá. 
Ao invés de fazer:
```
if NOT projectVM.isSubscription(project)
  if projectVM.isSubscription(project)
    aba de assinantes
  else
    aba de apoiadores
  end
```
Fazer:
```
if !projectVM.isSubscription(project)
  aba de apoiadores
end
```

Talvez também seja bom tirar o código referente ao conteúdo dessa aba (estatística de assinantes, listagem de assinantes e etc).

2021-08-16 14:58 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/project-tabs.js
> +                            : '',
Ou pelo menos fazer a remoção do código do conteúdo da aba em uma atividade/PR própria pra isso.

2021-08-16 16:21 UTC, stephannv approved these changes
Aprovando depois da @leticia-fernandes me informar que ainda vai ser definido o que fazer com o código antigo.

2021-08-18 14:29 UTC, devton approved these changes

2021-08-18 14:29 UTC, merged

2021-08-20 04:38 UTC, thiagocatarse commented
sandbox-ok