🐞 Ajusta indentação no email de projeto financiado
common-group/services-core pull request #1077
Opened 2021-09-21 12:20 UTC by leticia-fernandes

### Descrição
Corrige a indentação do arquivo para obedecer à sintaxe do `slim`.

### Referência
https://www.notion.so/catarse/Ajustar-tag-quebrando-no-e-mail-8c0576b7a66a424eadf9f40cbae8e4e0

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [X] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [X] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [X] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-09-21 21:52 UTC, stephannv approved these changes

2021-09-21 21:54 UTC, stephannv commented on services/catarse/app/views/catarse_bootstrap/user_notifier/mailer/contribution_project_successful.html.slim
>    |  incluindo você, teve #{contribution.project.total_contributors} apoiadores, foi financiado com sucesso no #{CatarseSettings[:company_name]}.
Esse texto todo tem que ficar dentro do `h2` mesmo?

2021-09-22 10:48 UTC, devton requested changes
pela identação ta tudo dentro do h2

2021-09-22 11:45 UTC, leticia-fernandes commented on services/catarse/app/views/catarse_bootstrap/user_notifier/mailer/contribution_project_successful.html.slim
>    |  incluindo você, teve #{contribution.project.total_contributors} apoiadores, foi financiado com sucesso no #{CatarseSettings[:company_name]}.
Eu me baseei no histórico do arquivo 
https://github.com/common-group/services-core/blob/0d074efaa8eeecccbc87b2ae727ea180a6626b02/services/catarse/app/views/catarse_bootstrap/user_notifier/mailer/contribution_project_successful.html.slim

2021-09-22 11:45 UTC, leticia-fernandes commented on services/catarse/app/views/catarse_bootstrap/user_notifier/mailer/contribution_project_successful.html.slim
>    |  incluindo você, teve #{contribution.project.total_contributors} apoiadores, foi financiado com sucesso no #{CatarseSettings[:company_name]}.
Mas falei com o Ton e vou ajustar :wink:

2021-09-22 12:03 UTC, stephannv commented on services/catarse/app/views/catarse_bootstrap/user_notifier/mailer/contribution_project_successful.html.slim
>    |  incluindo você, teve #{contribution.project.total_contributors} apoiadores, foi financiado com sucesso no #{CatarseSettings[:company_name]}.
Entendi.

2021-09-22 13:08 UTC, merged

2021-09-27 01:45 UTC, thiagocatarse commented
sandbox-ok