🐞 Cria validação de recompensa esgotada na contribuição.
common-group/services-core pull request #1078
Opened 2021-09-21 17:29 UTC by gabrielras

### Descrição
Um determinado usuário conseguiu criar um contribuição para um recompensa esgotada. Por isso foi criando uma validação no model de Contribuição para essa situação.

### Referência
https://www.notion.so/catarse/Validar-se-a-recompensa-esta-esgotada-ao-criar-uma-contribui-o-7034c3caedad4f9bade187550e910b27

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-09-22 10:56 UTC, devton requested changes

2021-09-22 10:56 UTC, devton commented on services/catarse/app/models/contribution.rb
> +  validate :reward_sold_out
@gabrielras essa validação tem que ser aplicada somente na hora da criação da contribuição, se manter no edit vai acabar travando de editar contribuições aonde a recompensa pode ter se esgotado mas que ja tinha sido selecionada

2021-09-22 15:05 UTC, gabrielras commented on services/catarse/app/models/contribution.rb
> +  validate :reward_sold_out
Ajustado.

2021-09-23 17:48 UTC, devton approved these changes

2021-09-23 18:04 UTC, stephannv approved these changes

2021-09-23 18:04 UTC, merged

2021-09-27 06:46 UTC, thiagocatarse commented
sandbox-ok