✨ Adiciona validação de endereço de pagamento no cadastro do cartão de crédito.
common-group/services-core pull request #1138
Opened 2021-11-11 12:14 UTC by gabrielras

### Descrição
Ao cadastrar um cartão de crédito é enviado um id do endereço de cobrança. É importante criar uma validação para verificar se o endereço do cartão pertence ao usuário do cartão.

### Referência
https://www.notion.so/catarse/Validar-que-endere-o-enviado-no-cadastro-do-cart-o-cr-dito-do-pr-prio-usu-rio-02dde4715a8847a49e01f032d75e77c4

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-11-11 12:36 UTC, leticia-fernandes commented on services/catarse/config/locales/billing.pt.yml
> +          invalid_billing_address: "endereço de combrança não corresponde ao endereço do usuário"
**Cosmético:**
`"endereço de **cobrança** não corresponde ao endereço do usuário"`

2021-11-11 12:40 UTC, leticia-fernandes approved these changes

2021-11-11 21:32 UTC, stephannv requested changes

2021-11-11 21:32 UTC, stephannv commented on services/catarse/spec/models/billing/credit_card_spec.rb
> +    context 'when billing address matches address user' do
```suggestion
    context 'when billing address owner matches user' do
```

2021-11-11 21:32 UTC, stephannv commented on services/catarse/spec/models/billing/credit_card_spec.rb
> +    context 'when billing address doesn`t match address user' do
```suggestion
    context 'when billing address owner doesn`t match user' do
```

2021-11-11 21:32 UTC, stephannv commented on services/catarse/spec/models/billing/credit_card_spec.rb
> +      let(:user) { address.user }
```suggestion
      let(:user) { create(:user) }
```

2021-11-11 21:32 UTC, stephannv commented on services/catarse/spec/models/billing/credit_card_spec.rb
> +      subject(:billing_credit_card) do
```suggestion
      subject(:credit_card) do
```

2021-11-11 21:32 UTC, stephannv commented on services/catarse/spec/models/billing/credit_card_spec.rb
> +      subject(:billing_credit_card) do
```suggestion
      subject(:credit_card) do
```

2021-11-17 13:05 UTC, stephannv approved these changes

2021-11-17 13:05 UTC, merged