🐞 Corrige texto na sessao sobre documentos fiscais
common-group/services-core pull request #1146
Opened 2021-11-29 12:52 UTC by priscilla-morimitsu

### Descrição
Na página de documentos fiscais, o texto foi alterado de "Você terá acesso aos documentos fiscais assim que seu projeto for encerrado e financiado." para "Você terá acesso aos documentos ficais assim que o saque do projeto for realizado com sucesso."

### Referência
https://www.notion.so/catarse/Alterar-texto-sobre-disponibiliza-o-dos-documentos-fiscais-e442c82748574dd0a8be6fb4ce4a7145

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-11-29 12:54 UTC, stephannv requested changes

2021-11-29 12:54 UTC, stephannv commented on services/catarse/config/locales/catarse_bootstrap/views/projects/edit.pt.yml
> +      nodoc_explanation: ' Você terá acesso aos documentos ficais assim que o saque do projeto for realizado com sucesso.'
Aqui falta só ajustar o "fiscais" que ficou "ficais"

2021-11-30 17:29 UTC, stephannv approved these changes

2021-11-30 19:09 UTC, merged

2021-12-13 02:59 UTC, thiagocatarse commented
sandbox-ok