✨ Adiciona validação no nível de apoio que pertence a um projeto de assinatura.
common-group/services-core pull request #1152
Opened 2021-12-09 16:48 UTC by gabrielras

### Descrição
Ao salvar nível de apoio (Tier), validar que o seu projeto é da modalidade Assinatura.

### Referência
[Link para a atividade
](https://www.notion.so/catarse/Validar-que-n-vel-de-apoio-pertence-a-um-projeto-de-assinatura-ad0131e36827452496155d77542240f9)

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2021-12-10 12:48 UTC, stephannv requested changes

2021-12-10 12:48 UTC, stephannv commented on services/catarse/app/models/membership/tier.rb
> +    end
**Sugestão**
```suggestion
    validate :project_mode_is_membership

    private

    def project_mode_is_membership
      return if project.try(:is_sub?)
      
      errors.add(:project_id, I18n.t('models.membership.tier.errors.invalid_project'))
    end
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/config/locales/membership.en.yml
> +          invalid_project: "project mode must be subscription."
```suggestion
          invalid_project: "project mode must be membership."
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/config/locales/membership.pt.yml
> +          invalid_project: "o projeto deve ter um modo de assinatura."
```suggestion
          invalid_project: "o projeto deve ser da modalidade assinatura."
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +      it 'doesn`t add invalid tier error' do
```suggestion
      it 'doesn`t add invalid project error' do
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +        expect(tier.errors[:invalid_project]).to be_empty
```suggestion
        expect(tier.errors[:project_id]).to be_empty
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +      end
**Sugestão:**
Não é necessário esse mock pois tu já está criando um subscription project, então na teoria o `is_sub?` já deve ser true por padrão.

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +        end
Sugestão:
Não é necessário esse mock pois tu já está criando projetos com outras modalidades, então na teoria o is_sub? já deve ser false por padrão.

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +        it 'adds invalid tier error message' do
```suggestion
        it 'adds invalid project error message' do
```

2021-12-10 12:48 UTC, stephannv commented on services/catarse/spec/models/membership/tier_spec.rb
> +          expect(tier.errors[:invalid_project]).to include error_message
```suggestion
          expect(tier.errors[:project_id]).to include error_message
```

2021-12-10 13:54 UTC, gabrielras commented on services/catarse/spec/models/membership/tier_spec.rb
> +          expect(tier.errors[:invalid_project]).to include error_message
@stephannv uma dúvida aqui, não consegui entender bem o motivo da mudança que vc pediu. Você quer que eu faça uma alteração aqui: models.membership.tier.errors.project_id ? pq caso contrário, acho que ele deveria capturar invalid_project mesmo não?

2021-12-11 11:39 UTC, gabrielras commented on services/catarse/app/models/membership/tier.rb
> +    end
Só uma dúvida pq não manter:
` validate :project_mode_is_membership, if: %i[project project_id]
`
e retornar dar um:
`return if project.is_sub?`

Não seria mais eficiente ele não rodar da validação caso não tenha os parâmetros project project_id que é o caso de alguns testes mockados?

2021-12-15 13:05 UTC, stephannv approved these changes

2021-12-15 13:05 UTC, merged