✨ Cria componente de banner
common-group/services-core pull request #1200
Opened 2022-02-05 00:22 UTC by priscilla-morimitsu

### Descrição
Criação do componente de banner sem utilização do storybook

### Referência
https://www.notion.so/catarse/Implementar-componente-banner-sem-precisar-do-Storybook-eadad7541b6b488e9161dfc8308af9cf

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2022-02-07 08:36 UTC, thiagocatarse requested changes
Oi @priscilla-morimitsu dei um passadão aqui pelo PR fazendo algumas sugestões, dá uma olhada e veja o que acha? Como é um PR que de certo modo vai ditar boa parte de como iremos mudar a forma como trabalhamos essa interação design - dev, achei melhor ser mais criterioso aqui, beleza?

E ao fazer esse processo de revisão eu já entendi um dos poderes do Storybook, que é justamente esse tipo de revisão também ser feito com a possibilidade de visualizarmos o componente. Mas isso a gente fala na reunião pra vermos se de fato é caso vencido aqui, ou se ainda tem alguma chance de olharmos para o Storybook mesmo.

2022-02-07 08:36 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/styles.scss
> +        strong {
Seguindo o caminho que falei no comentário abaixo, sobre usar estilos globais, a gente nem precisaria desse `strong` aqui, pois ali na `div` com o texto teríamos simplesmente usado a classe `.DesktopHeading`

2022-02-07 08:36 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/styles.scss
> +        p {
O mesmo aqui para o `p`, a gente não precisa dessa classe aqui, pois iremos usar na `div` ali a classe `DesktopBody` para esse texto sacou?

2022-02-07 08:36 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                        <p>{content}</p>
aqui seria um `<p class="DesktopBody">`

2022-02-07 08:36 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                            <strong>{heading}</strong>
E aqui seria `<div class="DesktopHeading">`

2022-02-07 08:36 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/styles.scss
> +    .banner-inner-content {
Aqui tem uma opção que podemos testar que é usar o `gap` do `flex layout` (isso não fica evidente ali no Inspector do Figma e podemos conversar sobre como podemos deixar isso mais claro na hora de passarmos o arquivo do figma pros devs, mas a forma como o Figma entende os espaços entre elementos dentro de uma caixa é exatamente como o gap do flexbox funciona no CSS.

Nesse caso aqui por exemplo, eu vi que você tinha colocado uma `margin-bottom:4px` ali no `strong`, mas nem precisamos, pois podemos simplesmente colocar um `gap:4px` aqui no `banner-inner-content` por exemplo e já funciona.

2022-02-07 08:37 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                        <p>{content}</p>
PS: chamei de DesktopBody, mas vc vai ver lá no Notion que fiz duas propostas de arquivos globais lá, uma com kebab-case onde teríamos chamado aqui de text-style-desktop-body por exemplo.

2022-02-07 18:19 UTC, priscilla-morimitsu commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/styles.scss
> +            color: #3F4752;
@thiagocatarse verdade! Eu tinha me esquecido disso, mas é uma boa sim! Vou fazer essa correção.

2022-02-08 13:14 UTC, stephannv requested changes

2022-02-08 13:14 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                                    <button
**Sugestão**
Penso que nesse caso aqui tu pode usar o javascript a teu favor pra deixar o html mais limpo, por exemplo, lá no começo do código:
```javascript
const hasPrimaryButton = !!(buttonPrimaryLabel && buttonPrimaryOnClick)
const hasSecondaryButton = !!(buttonSecondaryLabel && buttonSecondaryOnClick)
const hasActions = hasPrimaryButton || hasSecondaryButton
```

Daí na declaração do html, tu vai ter variáveis com nome mais significativos e regras um pouco menos complexas, vai ficar um pouco mais fácil de manter.

Também tu pode dar uma olhada no componente `If` que já tem no projeto (busca por `</If>` que tu encontra). Daí fica melhor que os a || b && ( html ).

2022-02-08 21:38 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                            <strong>{heading}</strong>
@stephannv isso, eu acabei não atualizando esses comentários. Na real eu compartilhei um arquivo com a @priscilla-morimitsu chamado GlobalStyles (veja aqui https://www.notion.so/catarse/Catarse-Design-System-af4c15b3ddab4b12b1c78b4ffcb00827#29e6b10419e0498eaf7e3a5805b7b2cd), que contém as variáveis de cor e os estilos de Texto.

Nesse arquivo as classes de texto sempre começam com `.text-style-` e então o nome da classe. Então aqui não seria `.DesktopHeading` não. Seria na real `.text-style-heading`

2022-02-08 21:38 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                            <strong>{heading}</strong>
E então vc vai ver que lá usamos as media-queries, como vc falou, sacou?

2022-02-11 11:32 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +                            <strong>{heading}</strong>
Boa, @thiagocatarse.

2022-02-22 14:17 UTC, stephannv requested changes

2022-02-22 14:17 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Atom/Button/styles.scss
> +}
**Dúvida**
Estou meio por fora do css, mas a boa prática não seria definir os tamanhos em rem/em? Digo isso por olhar o código fonte de alguns frameworks css e eles definirem os tamanhos dos botões com rem/em.
Aqui o halfmoon css
<img width="378" alt="Screen Shot 2022-02-22 at 10 55 48" src="https://user-images.githubusercontent.com/3025661/155146965-58e87704-0e56-4055-a9a8-fcf6bfc5102a.png">

Aqui o bootstrap
<img width="454" alt="Screen Shot 2022-02-22 at 11 01 54" src="https://user-images.githubusercontent.com/3025661/155147666-311b48dc-b264-495b-9835-75cda0eca6e0.png">

2022-02-22 14:17 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Atom/Icon/index.tsx
> +// import './styles.scss';
**Cosmético**
Remover comentário.

2022-02-22 14:17 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Atom/Icon/index.tsx
> +    color = "#5C5F62",
**Dúvida**
Essa cor padrão não poderia ser uma variável do tema que estamos criando?

2022-02-22 14:17 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +import './styles.scss';
**Sugestão**
Usar o `@/path/para/arquivo` ao invés dos `../..`, assim fica mais fácil entender de onde vêm os arquivos.

2022-02-23 13:36 UTC, devton approved these changes

2022-03-03 02:08 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Atom/Button/styles.scss
> +}
Sim, de fato pode ser uma boa. A questão do `rem` é que ele é a prática mais recomendável para acessibilidade né, pois caso a pessoa altere as configurações nativas do browser (pois tem problemas de vista por exemplo, e quer ver tudo "aumentado"), o `rem` faz esse escalonamento automático. Tem gente que usa `rem` só nas fontes, mas pelo que eu li o ideal é adotarmos o `rem` para tudo mesmo (pois imagina um botão que fica com a fonte muito grande, mas os espaçamentos todos esprimidos por exemplo né).

Agora esse halfmoon parece usar alguma abordagem ali para fazer com que a matemática de conversão PX > REM seja a mais "no brain" possível pelo que eu vi. Pois quando eles usam 2.6rem por exemplo, isso significa 26px. Acho que se formos por esse caminho pode fazer sentido, pelo que eu entendo aqui o que precisamos fazer então é colocar o :root { font-size: 62.5% }, pois assim a nossa conversão para rem vai sempre ser tranquila de fazer.

(obviamente algumas coisas não precisam ter rem, e isso é que precisamos definir - exemplo a largura de uma borda - nesse caso se é 1px, tem que ser 1px mesmo, pois não precisamos escalar uma borda por exemplo).

2022-03-03 02:08 UTC, thiagocatarse commented on services/catarse/catarse.js/legacy/src/components/Atom/Icon/index.tsx
> +    color = "#5C5F62",
Sim, deveria ser mesmo

2022-03-07 18:19 UTC, stephannv commented
Colocando em rascunho aqui para corrigir esses dois commits

2022-03-11 23:48 UTC, stephannv requested changes

2022-03-11 23:48 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Atom/Button/index.tsx
> +import { Icon } from '../../Atom/Icon';
**Sugestão**
Usar o alias pra evitar o uso dos `../../..`, ex.: `import { If } from '@/shared/components/if'`

2022-03-11 23:48 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/components/Molecule/Banner/index.tsx
> +import { Icon } from '../../Atom/Icon';
**Sugestão**
Usar o alias pra evitar o uso dos `../../..`, ex.: `import { If } from '@/shared/components/if'`

2022-03-11 23:48 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/root/users/edit/#balance/index.tsx
> +import { Banner } from '../../../../components/Molecule/Banner'
**Sugestão**
Usar o alias pra evitar o uso dos `../../..`, ex.: `import { Banner } from '@/components/Molecule/Banner'`

2022-03-15 12:14 UTC, merged

2022-03-30 02:57 UTC, thiagocatarse commented
sandbox-ok