✨ Adiciona integração com e-notas nas actions de project_fiscal.
common-group/services-core pull request #1245
Opened 2022-03-16 16:46 UTC by gabrielras

### Descrição
Atualmente temos a integração com e-notas, mas ela não tem integração com a action de criação de project_fiscal. Essa atividade permite gerar a nf durante a geração do project_fiscal.

### Referência
[Link para a atividade
](https://www.notion.so/catarse/Adicionar-integra-o-com-emiss-o-de-NF-assim-que-um-project-fiscal-for-criado-4e4973cb50c84e128df65843e49b29cc)

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] ~~A base de conhecimento foi atualizada~~

2022-03-18 12:29 UTC, devton requested changes
Acho que seria uma boa salvar a informação da NF no registro ali do project_fiscal, pra conseguir saver quais project_fiscal tem NF

2022-03-18 13:09 UTC, stephannv approved these changes

2022-03-20 12:42 UTC, gabrielras commented
Agora é possível salvar em metadata as informações do e-notas.

2022-03-21 11:22 UTC, devton approved these changes

2022-03-21 11:22 UTC, merged

2022-03-28 10:28 UTC, devton commented
sandbox-ok