✨ Adiciona validação para verificar imagens base64 no corpo do projet…
common-group/services-core pull request #514
Opened 2020-10-06 19:44 UTC by leticia-fernandes

…o e no orçamento

### Descrição

Adiciona validação para verificar imagens base64 no corpo do projeto e no orçamento.

### Referência

https://www.notion.so/catarse/ae4f80371ac34954be3b3aa78597f89e?v=ad877bd2538d4d489efc34103bbb6898&p=f8598d3af82f41078370781b4f251980

### Antes de criar esse pull request confira se:

- [X]  Testes estão implementados
- [X]  Descreveu o propósito do commit com o emoji no início da mensagem
- [X]  Mudanças estão unificadas em um único commit
- [X]  Revisou seu próprio código
- [ ]  A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2020-10-06 20:00 UTC, stephannv requested changes

2020-10-06 20:00 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +    context 'when budget has base64 images' do
Aqui também seria bom testar que a mensagem de erro não é adicionada naquele campo quando não há imagens em base64 nele.

2020-10-07 11:05 UTC, thiagocatarse commented on services/catarse/app/models/concerns/project/custom_validators.rb
> +      errors.add(:budget, :invalid)     if budget.match('data:image/.*;base64')
Pode usar:

"O formato de imagem base64 não é permitido. Por favor, inclua imagens usando o botão de adicionar imagens do editor de texto. [Saiba como aqui.](https://suporte.catarse.me/hc/pt-br/articles/360023812172-Como-adicionar-imagens-e-v%C3%ADdeos-%C3%A0-descri%C3%A7%C3%A3o-do-projeto-)"

2020-10-07 11:13 UTC, thiagocatarse commented on services/catarse/app/models/concerns/project/custom_validators.rb
> +      errors.add(:budget, :invalid)     if budget.match('data:image/.*;base64')
Fiz a sugestão aqui em cima @leticia-fernandes @stephannv

2020-10-08 15:09 UTC, stephannv requested changes

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +        project.save
Aqui tu pode chamar apenas um `project.valid?`, que ele já adiciona os errors se houverem. Esse comentário vale pros outros `project.save` que tem nesse pull request.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +      it do
Não é mais necessário, pois os outros testes que tu fez já cobrem que o objeto é inválido.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +      it do
Não é mais necessário, pois os outros testes que tu fez já cobrem que o objeto é inválido.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +        expect(project.errors[:about_html]).not_to include I18n.t('activerecord.errors.models.project.attributes.about_html.invalid')
Os matchers to rspec aceitam que tu use `not_to` ou `to_not`, pra ficar mais legível nesses casos, é melhor o `to_not`.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +      it do
Não é mais necessário, pois os outros testes que tu fez já cobrem que o objeto é inválido.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +      it do
Não é mais necessário, pois os outros testes que tu fez já cobrem que o objeto é inválido.

2020-10-08 15:09 UTC, stephannv commented on services/catarse/spec/models/concerns/project/custom_validators_spec.rb
> +      it 'don\'t add error message to budget' do
Pra não ter que ficar colocando \' nos teus testes, tu pode usar o \`.
Exemplo:
Ao invés de `don\'t` tu pode fazer ```don`t```

2020-10-12 22:27 UTC, stephannv approved these changes

2020-10-15 21:17 UTC, merged