🐞 Atualizacao de cache para novos status do projeto.
common-group/services-core pull request #636
Opened 2020-12-09 17:10 UTC by gabrielras

### Descrição
Depois que o projeto sai do status online, os cache de recompensa e projeto param de atualizar. Precisamos colocar os status waiting_funds, failed, successful na rotina em que atualiza os cache.

### Referência
https://www.notion.so/catarse/Atualizar-rake-de-atualiza-o-de-cache-para-atualizar-tamb-m-projetos-finalizados-5930ff429a8840bb9df8f821e27efa4d

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2020-12-09 19:31 UTC, stephannv approved these changes

2020-12-09 19:33 UTC, stephannv commented on services/catarse/lib/tasks/dispatch_project_metric_storage_refresh_task.rake
> +      .where(projects: {state: [:online, :waiting_funds, :failed, :successful]})
**Cosmético:**
Nas próximas vezes, quando for criar um array de symbols, pode fazer assim:
```suggestion
      .where(projects: { state: %i[online waiting_funds failed successful] })
```

2020-12-10 12:20 UTC, devton commented on services/catarse/lib/tasks/dispatch_project_metric_storage_refresh_task.rake
> +      .where(projects: {state: [:online, :waiting_funds, :failed, :successful]})
O status successful e failed vão sempre passar em todos os projetos, o ideal aqui é deixar apenas o online e waiting funds e disparar a chamada do worker na troca de status dos projetos

2020-12-10 12:21 UTC, devton requested changes
O status successful e failed vão sempre passar em todos os projetos, o ideal aqui é deixar apenas o online e waiting funds e disparar a chamada do worker na troca de status dos projetos

2020-12-10 12:21 UTC, devton commented on services/catarse/lib/tasks/dispatch_project_metric_storage_refresh_task.rake
> +      .where(projects: {state: [:online, :waiting_funds, :failed, :successful]})
O status successful e failed vão sempre passar em todos os projetos, o ideal aqui é deixar apenas o online e waiting funds e disparar a chamada do worker na troca de status dos projetos

2020-12-10 13:42 UTC, stephannv approved these changes

2020-12-15 20:56 UTC, stephannv commented
Depois dá uma investiga nesses testes @gabrielras.

2021-01-05 22:03 UTC, devton approved these changes

2021-01-05 22:04 UTC, merged

2021-01-06 22:22 UTC, devton commented
sandbox-ok