✨ Adiciona funcionalidade de transferência de saldo.
common-group/services-core pull request #654
Opened 2020-12-16 12:09 UTC by leticia-fernandes

### Descrição
Funcionalidade de transferência de saldo para dar mais autonomia ao atendimento e diminuir o fluxo de tickets de chore.

### Referência
https://www.notion.so/catarse/Tarefas-gerais-de-Produto-f085463d388348bb85b32c8b72ed9342?p=e16822f66e5647689ac2d7601a90285e

### Antes de criar esse pull request confira se:
- [X] Testes estão implementados
- [X] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [X] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [X] Revisou seu próprio código
- [X] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2020-12-16 14:04 UTC, stephannv requested changes

2020-12-16 14:04 UTC, stephannv commented on services/catarse/spec/controllers/admin/balance_transactions_controller_spec.rb
> +    context "When user has admin roles" do
**Cosmético:**
Usar letra minúscula no início dos describe, context e it pra manter a padronização.

2020-12-16 14:04 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +                        <label for="name">Id do destinatário:</label>
**Dúvida:**
O padrão de mostrar textos no front-end não seria usar o I18n do Rails?

2020-12-16 14:04 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +import { withHooks } from "mithril-hooks"
**Dúvida:**
Esses novos componentes não terão testes?

2020-12-16 18:27 UTC, leticia-fernandes commented on services/catarse/spec/models/balance_transaction_spec.rb
> +          expect(subject).to_not be_nil
Era uma forma de ter um teste a mais e tbm pra poder chamar o `subject`, senão ele não é ativado. Nesse caso eu posso substituir só pelo `subject` nessa linha.

2020-12-16 18:44 UTC, leticia-fernandes commented on services/catarse/spec/controllers/admin/balance_transactions_controller_spec.rb
> +    let(:sender) { create(:user) }
Mas aqui no `controller` ficou como `sender` e `receiver`. No model eu mudei pra `from_user` e `to_user`.

2020-12-16 18:45 UTC, leticia-fernandes commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +import { withHooks } from "mithril-hooks"
![image](https://user-images.githubusercontent.com/33899639/102392349-b39d6800-3fb5-11eb-826a-882de2f75a10.png)

2020-12-16 18:46 UTC, leticia-fernandes commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +                        <label for="name">Id do destinatário:</label>
![image](https://user-images.githubusercontent.com/33899639/102392420-cadc5580-3fb5-11eb-80ef-a003d19bef4f.png)

2020-12-16 18:51 UTC, stephannv commented on services/catarse/spec/controllers/admin/balance_transactions_controller_spec.rb
> +    let(:sender) { create(:user) }
@leticia-fernandes no model já era `from_user` e `to_user`.
Nos controllers e nos testes que sugiro que altere para `from_user` e `to_user` para seguir justamente o padrão do modelo e não ficar com nomenclaturas diferentes espalhada pelo código para se referir às mesmas coisas.

2020-12-16 19:31 UTC, leticia-fernandes commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +import { withHooks } from "mithril-hooks"
acredito que o @grpse pode responder melhor :sweat_smile:

2020-12-17 12:31 UTC, stephannv approved these changes

2020-12-17 12:31 UTC, stephannv commented on services/catarse/spec/controllers/admin/balance_transactions_controller_spec.rb
> +        it 'returns `bad_request` http response' do
**Cosmético:**
```suggestion
        it 'returns `unprocessable_entity` http response' do
```

2020-12-17 12:31 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance.tsx
> + * window.c.AdminResetPassword component
**Cosmético:**
Verificar com o @grpse se estamos mantendo essa documentação. Se sim, precisa atualizar o conteúdo pra refletir o componente em questão. Se não, pode remover esses comentários.

2020-12-17 12:31 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +                    <input onclick={nextStep} type="submit" value="Próximo passo" data-wait="Aguarde..." class="btn btn-small w-button"/>
**Cosmético:**
Faltou usar o i18n nesse botão.

2020-12-17 12:31 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-user-detail.js
> +                    innerLabelBalanceInfo: 'Para transferir o saldo total, deixe este campo em branco.',
**Cosmético:**
Faltou o i18n nesses textos também.

2020-12-17 12:31 UTC, stephannv commented on services/catarse/spec/models/balance_transaction_spec.rb
> +    subject { BalanceTransaction.
**Cosmético:**
Juntar isso em uma linha só. Ainda não temos um styleguide pro nosso código, mas podemos usar 120 colunas como um valor seguro. E quando precisarmos quebrar uma linha, o `.` vai para a linha de baixo, por exemplo:
```ruby
foo
  .do
  .something
```

2020-12-17 14:29 UTC, stephannv approved these changes

2020-12-17 14:29 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance.tsx
> +                    return (
**Sugestão:**
@grpse e @leticia-fernandes não seria o caso de mover esse confirm pro seu próprio componente também? Assim segue a mesma organização do Start e do Success.

2020-12-17 18:40 UTC, grpse commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance-start.tsx
> +import { withHooks } from "mithril-hooks"
@stephannv nem todos os componentes tem teste. Se encontrar uma forma interessante de testar eles individualmente vai ser ótimo @leticia-fernandes.

2020-12-17 18:41 UTC, grpse commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance.tsx
> + * window.c.AdminResetPassword component
@stephannv podemos remover, esse tipo de documentação fica outdated muito fácil.

2020-12-17 18:42 UTC, grpse commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance.tsx
> +                    return (
@leticia-fernandes se possível seguir a orientação do @stephannv seria muito melhor pra entender a estrutura das telas.

2020-12-17 18:44 UTC, grpse commented on services/catarse/catarse.js/legacy/src/c/admin-transfer-balance.tsx
> +        return m('.w-col.w-col-2', [
**Sugestão**:
@leticia-fernandes trocar essa sintaxe de `m('...` para a de JSX aqui para manter o padrão do restante dos componentes.
Criar um novo componente com somente o que está dentro da função `transferStateComponente()`.

2021-01-07 20:27 UTC, devton approved these changes

2021-01-11 18:08 UTC, grpse approved these changes
Muito boa a refatoração dos componentes.

2021-01-14 00:25 UTC, merged

2021-01-14 21:03 UTC, devton commented
sandbox-ok