🐞 Ajusta id de recompensa invalido ao atualizar cache.
common-group/services-core pull request #715
Opened 2021-01-19 13:19 UTC by gabrielras

### Descrição
Devemos ajustar id de recompensa invalido em rotina de atualizar cache de recompensas, pois ao utilizar sp.reward_id e não sp.reward.id ele é passado no formado do comum. 

### Referência
https://www.notion.so/catarse/Ajustar-id-de-recompensa-invalido-em-rotina-de-atualizar-cache-de-recompensas-7fb636fac0064b13ae5772f4d89c2313

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-01-19 13:29 UTC, devton requested changes

2021-01-19 13:29 UTC, devton commented on services/catarse/lib/tasks/common.rake
> +          RewardMetricStorageRefreshWorker.perform_async(sp.reward.id)
@gabrielras aqui acho que podemos colocar um if pra caso a recompensa não exista

2021-01-19 13:42 UTC, gabrielras commented on services/catarse/lib/tasks/common.rake
> +          RewardMetricStorageRefreshWorker.perform_async(sp.reward.id)
Massa, adicionado :)

2021-01-19 13:43 UTC, merged

2021-01-20 22:30 UTC, thiagocatarse commented
sandbox-ok