🐞 Ajuste no reembolso de boleto na ação de banir projeto
common-group/services-core pull request #774
Opened 2021-03-03 18:18 UTC by gabrielras

### Descrição
É preciso implementar a chamada de reembolso do comum no catarse. Atualmente essa chamada não existe e não altera o status do pagamento.

### Referência
https://www.notion.so/catarse/Ajustar-a-o-de-banir-projetos-em-reembolso-de-boleto-61ddebd92da7425d80c2f7f8d8681833

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-03-03 22:40 UTC, grpse approved these changes

2021-03-04 13:33 UTC, stephannv approved these changes

2021-03-15 12:10 UTC, devton requested changes

2021-03-15 12:10 UTC, devton commented on services/catarse/app/models/common_wrapper.rb
> +  def refund_subscription(resource)
@gabrielras so renomeia esse metodo aqui pra se chamar refund_subscription_payment, pq so subscription da a entender que a gente vai reembolsa a assinatura e não o pagamento

2021-03-15 12:33 UTC, gabrielras commented on services/catarse/app/models/common_wrapper.rb
> +  def refund_subscription(resource)
vdd @devton, vou alterar.

2021-03-15 13:22 UTC, devton approved these changes

2021-03-15 13:22 UTC, merged