🐞 Renomear arquivo de imagem ao fazer upload
common-group/services-core pull request #788
Opened 2021-03-12 13:01 UTC by grpse

### Descrição
Muda o nome do arquivo de imagem quando faz o upload. Copiei as instruções do CarrierWave: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Create-random-and-unique-filenames-for-all-versioned-files

### Referência
https://www.notion.so/catarse/Adicionar-etapa-para-tirar-caracteres-especiais-quando-fizer-o-upload-de-imagens-839ce49d5d264634af684982d954b101

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [ ] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-03-12 13:16 UTC, stephannv approved these changes

2021-03-12 13:34 UTC, grpse commented
Aconteceram alguns erros ali pois no teste esperava um nome específico do arquivo. Vou corrigir o teste ali.

2021-03-16 12:20 UTC, stephannv requested changes

2021-03-16 12:20 UTC, stephannv commented on services/catarse/spec/rails_helper.rb
> +
**Problema**
Não é bom colocar essas coisas no `rails_helper.rb`, a gente tenta manter ele o mais limpo possível. Então temos 2 opções:
- Colocar isso nos helpers.
- Colocar diretamente no teste que precisa.

Como são apenas 2 testes, eu sugiro colocar só o 
```ruby
let(:uuid_regexp) { /[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}/ }
``` 
nos testes que precisarem dele.

2021-03-16 12:55 UTC, grpse commented on services/catarse/spec/rails_helper.rb
> +
Ajustado (agora foi para perto de onde está sendo usado).

2021-03-18 14:11 UTC, devton approved these changes

2021-03-18 14:11 UTC, stephannv approved these changes

2021-03-18 14:32 UTC, merged

2021-03-22 08:16 UTC, thiagocatarse commented
sandbox-ok