🐞 Válida imagens de base64 nas novidades.
common-group/services-core pull request #799
Opened 2021-03-23 11:52 UTC by gabrielras

### Descrição
Ao adicionar ma imagem na novidade arrastando ela pelo editor, a imagem é enviada como base64. O problema é que os clientes de e-mail como gmail não renderiza a imagem internamente. A solução é adicionar uma validação em project_post.

### Referência
https://www.notion.so/catarse/Valida-o-de-imagem-base64-nas-novidades-948f4c57e59e48e590fe066fe6a18342

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-03-23 11:53 UTC, gabrielras commented on services/catarse/catarse.js/legacy/src/root/posts.js
> +            },
Adicionado validação da base64 no frontend.

2021-03-23 11:55 UTC, grpse approved these changes

2021-03-23 12:37 UTC, stephannv requested changes

2021-03-23 12:37 UTC, stephannv commented on services/catarse/config/locales/catarse_bootstrap/views/projects/edit.en.yml
> +      base64_images_not_allowed: Base64 images are not allowed. Please, upload images using the upload button. <a target='_blank' href='https://suporte.catarse.me/hc/pt-br/articles/360023812172-Como-
**Sugestão**
Não precisa adicionar mais chaves dessas nos locales pois já temos essa mensagem definida de forma global no `locales/pt.yml` e `locales/en.yml`. Talvez tenha que investigar no `window.i18n.t` como fazer para acessar essas mensagens globais.

2021-03-23 12:46 UTC, gabrielras commented on services/catarse/config/locales/catarse_bootstrap/views/projects/edit.en.yml
> +      base64_images_not_allowed: Base64 images are not allowed. Please, upload images using the upload button. <a target='_blank' href='https://suporte.catarse.me/hc/pt-br/articles/360023812172-Como-
show, ajustei para ter acesso global.

2021-03-24 14:53 UTC, stephannv approved these changes

2021-03-24 19:29 UTC, merged