✨ Evita duplicação de cartão de crédito.
common-group/services-core pull request #872
Opened 2021-05-12 16:29 UTC by gabrielras

### Descrição
Atualmente quando o card id da transação seja um que já exista na nossa base de dados nós salvamos ele novamente, a alteração evita a duplicação de cartão de créditos já salvos.

### Referência
https://www.notion.so/catarse/Evitar-duplica-o-de-cart-o-de-cr-ditos-113e6c18e7904115b062da23e9bd87de

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-12 16:37 UTC, stephannv requested changes

2021-05-12 16:37 UTC, stephannv commented on services/catarse/app/actions/billing/payments/authorize_transaction.rb
> +      end
**Problema**
Nessa implementação, quando o card_hash é de um cartão que já está na nossa base, o pagamento fica sem referência para esse cartão de crédito. Ex.: Depois de fazer um `payment.credit_card`, o retorno será nil, pois não foi feito o link entre o cartão existente e o pagamento.

2021-05-13 11:15 UTC, stephannv requested changes

2021-05-13 11:15 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      expect(payment.credit_card_id).not_to eq(nil)
**Problema**
Melhorar cobertura e descrição dos testes. No código há 3 situações possíveis: pagamento com billing::creditcard, pagamento feito com card hash de um cartão que existe na nossa base, pagamento com card hash de um cartão que não existe na base. Mas aqui só

2021-05-13 17:10 UTC, stephannv requested changes

2021-05-13 17:10 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +    end
**Problema**
Melhorar legibilidade da mensagen do `it`.

Pra garantir que o result está fazendo o que é pra fazer, tu pode colocar antes dele ou no before um `payment.update!(credit_card_id: nil)`, assim tu garante que o pagamento que está sendo testado não terá cartão de crédito, pois se por algum motivo alguém muda a criação da factory no início do arquivo pra criar o pagamento já com cartão de crédito, esses teus testes podem dar um falso positivo.

2021-05-13 17:10 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
>      end
**Sugestão**
Pode remover esse teste, pois os outros contextos já estão testando que o cartão de crédito estará preenchido.

2021-05-14 13:22 UTC, stephannv requested changes

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'credit card was not created' do
```suggestion
      it 'doesn`t create a credit card' do
```

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'payment remains with same credit card' do
```suggestion
      it 'doesn`t change payment credit card' do
```

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +            gateway: Faker::Lorem.word,
**Sugestão**
Aqui tu pode deixar o mesmo gateway do pagamento, para garantir que ele não foi utilizado porque era de outro usuário.

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +        expect { result }.to change(Billing::CreditCard, :count).by(0)
**Cosmético**
Utilizar a sintaxe `expect { result }.not_to change(Billing::CreditCard, :count)`, pois fica mais legível.

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +            gateway: Faker::Lorem.word,
**Sugestão**
Aqui tu pode usar o mesmo gateway do outro cartão, pra garantir que ele não foi encontrado por percenter a outro usário, e não porque ele tinha um gateway diferente.

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'credit card was not created' do
```suggestion
      it 'doesn`t create credit card' do
```

2021-05-14 13:22 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'payment remains with same credit card' do
```suggestion
      it 'assigns found credit card to payment' do
```

2021-05-17 11:17 UTC, stephannv requested changes

2021-05-17 11:17 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'assigns found credit card to payment' do
```suggestion
      it 'doesn`t change payment credit card' do
```

2021-05-17 11:17 UTC, stephannv commented on services/catarse/spec/actions/billing/payments/authorize_transaction_spec.rb
> +      it 'creates credit card with given attributes' do
```suggestion
      it 'assigns created credit card to payment' do
```

2021-05-17 17:33 UTC, leticia-fernandes approved these changes

2021-05-18 02:47 UTC, devton reviewed
@gabrielras acha que vale colocar um indice unico na tabela também?

2021-05-18 12:43 UTC, stephannv approved these changes

2021-05-18 12:43 UTC, merged