✨ Válida integridade do valor no campo total_amount_cents
common-group/services-core pull request #884
Opened 2021-05-18 10:15 UTC by gabrielras

### Descrição
É preciso adicionar uma validação ao pagamento garantindo que o total_amount é igual ao amount + shipping_fee + payment_method_fee. E se o valor estiver inválido, enviar uma mensagem de erro personalizada.

### Referência
https://www.notion.so/catarse/Validar-integridade-dos-valores-do-pagamento-69898e388f884b14acf38259f9c6d015

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-18 11:32 UTC, stephannv requested changes

2021-05-18 11:32 UTC, stephannv commented on services/catarse/app/models/billing/payment.rb
> +    before_save :total_amount_valid?
**Sugestão**
Ao invés de usar o `before_save`, usar o `validate`

2021-05-18 11:32 UTC, stephannv commented on services/catarse/app/models/billing/payment.rb
> +      raise ActiveRecord::Rollback
**Sugestão**
Usando o `validate` não precisa desse raise.

2021-05-18 11:32 UTC, stephannv commented on services/catarse/config/locales/billing_payment.en.yml
> +en:
**Sugestão**
Cria um arquivo yml só para os modelos do billing, pois se criamos um yml pra cada modelo, vai ficar gigante. O mesmo se aplica para o pt.

2021-05-18 11:32 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +  describe '#before_save' do
**Sugestão**
Com a mudança para o `validate`, isso vai para dentro do `describe 'Validations'`. E quando vamos testar validations, não podemos fazer só um `expect(obj.save).to be_falsey`, pois não conseguimos garantir que a falha ao salvar foi relacionado com nossa validação. Temos que verificar se o objeto está com o erro que era pra estar devido a falha na validação. Também não é necessário criar um pagamento só pra isso, um `Billing::Payment.new` preenchendo os campos desejados já basta pra testar esse caso.

2021-05-18 17:07 UTC, devton approved these changes

2021-05-18 17:08 UTC, stephannv requested changes

2021-05-18 17:08 UTC, stephannv commented on services/catarse/config/locales/billing.en.yml
> +          total_amount_valid: "doesn't match other values"
```suggestion
          invalid_total_amount: "doesn't match other values"
```

2021-05-18 17:08 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +    context 'when total amount cents is valid' do
```suggestion
    context 'when total amount cents doesn`t represent sum of amount and fees' do
```

2021-05-18 17:08 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +        )
**Sugestão**
Pra facilitar, aqui tu pode usar  os atributos sem os cents, exemplo: `total_amount: 50, amount: 20, ...`.

2021-05-18 17:08 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +      end
```suggestion
      it 'doesn`t add invalid_total_amount error' do
        payment.valid?

        expect(payment.errors[:total_amount_cents]).to be_empty
      end
```

2021-05-18 17:08 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +    end
```suggestion
      it 'adds invalid total amount error message' do
        payment.valid?

        error_message = I18n.t('models.billing.payment.errors.total_amount_valid')
        expect(payment.errors[:total_amount_cents]).to include error_message
      end
    end
```

2021-05-19 11:51 UTC, stephannv requested changes

2021-05-19 11:51 UTC, stephannv commented on services/catarse/app/models/billing/payment.rb
> +
**Problema**
A chave do erro `total_amount_valid` precisa ser atualizada.

**Sugestão**
E esse método deve ser privado, pois não há motivos para ele ser público, ele não será utilizado externamente, apenas internamente no momento da validação.

2021-05-19 11:51 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +      end
**Cosmético**
Provavelmente isso aqui consiga ficar numa linha só.

2021-05-19 11:51 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +        error_message = I18n.t('models.billing.payment.errors.total_amount_valid')
**Problema**
A chave `total_amount_valid` precisa ser atualizada.

2021-05-19 12:29 UTC, stephannv approved these changes

2021-05-19 12:29 UTC, merged