✨ Adiciona funcionalidade de reembolso de assinatura
common-group/services-core pull request #888
Opened 2021-05-18 18:49 UTC by leticia-fernandes

### Descrição
Funcionalidade implementada para diminuir a incidência de tickets e dar mais autonomia ao atendimento.
Adiciona um botão `Reembolsar` ao lado de pagamento com status `paid` no admin de assinaturas.

### Referência
https://www.notion.so/catarse/Implementar-bot-o-no-admin-assinaturas-para-reembolsar-apoio-mensal-f0f03c43b30e4df98ab9699f13e39820

### Antes de criar esse pull request confira se:
- [X] Testes estão implementados
- [X] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [X] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [X] Revisou seu próprio código
- [X] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-18 18:50 UTC, leticia-fernandes commented on services/catarse/app/models/concerns/subscription_payments/refund_handler.rb
> +      transaction.refund if transaction.payment_method == 'credit_card' && transaction.status == 'paid'
**Atenção**: Esse PR já foi revisado e aprovado. Porém a única linha alterada nesse PR foi essa :point_up_2:

2021-05-18 18:55 UTC, stephannv approved these changes

2021-05-18 19:10 UTC, leticia-fernandes commented on services/catarse/spec/models/subscription_payment_spec.rb
> +
...então tive que alterar os testes também.

2021-05-18 19:14 UTC, stephannv commented on services/catarse/spec/models/subscription_payment_spec.rb
> +    end
**Dúvida**
Aqui não era pra ser o contrário? Quando a transação é paga e o método de pagamento é cartão de crédito, o reembolso era pra acontecer.

2021-05-18 19:19 UTC, leticia-fernandes commented on services/catarse/spec/models/subscription_payment_spec.rb
> +    end
![image](https://user-images.githubusercontent.com/33899639/118710557-d649dc00-b7f4-11eb-880a-97ee709eb515.png)

2021-05-18 19:28 UTC, leticia-fernandes commented on services/catarse/spec/models/subscription_payment_spec.rb
> +
...então tive que alterar os testes também!²

2021-05-18 19:34 UTC, stephannv requested changes

2021-05-18 19:34 UTC, stephannv commented on services/catarse/spec/models/subscription_payment_spec.rb
> +    let(:transaction) { double(status: 'paid', refund: true, payment_method: 'boleto') } # rubocop:disable RSpec/VerifiedDoubles
**Sugestão**
Deixar aqui como cartão de crédito por padrão, e onde for necessário, mudar o meio de pagamento para outro.

2021-05-18 19:34 UTC, stephannv commented on services/catarse/spec/models/subscription_payment_spec.rb
> +        double(PagarMe::Transaction, status: 'refunded', refund: true, payment_method: 'boleto') # rubocop:disable RSpec/VerifiedDoubles
**Sugestão**
Deixando o status refunded e o método de pagamento boleto, tu não consegue saber que se a transação não foi reembolsada por ela ser boleto ou por estar reembolsada. Ou seja, alguém tirar uma dessas condições do código, esse teste vai passar. Então o ideal é tu deixar o cenário todo perfeito pra ser reembolsada e alterar só o critério que tu quer testar, que no caso é o status da transação.

2021-05-18 20:00 UTC, leticia-fernandes commented on services/catarse/spec/models/subscription_payment_spec.rb
> +        double(PagarMe::Transaction, status: 'refunded', refund: true, payment_method: 'boleto') # rubocop:disable RSpec/VerifiedDoubles
Fiz um ajuste agr, mas não tenho certeza se foi o que tu quis dizer....

2021-05-18 21:42 UTC, stephannv approved these changes

2021-05-18 21:42 UTC, stephannv commented on services/catarse/spec/models/subscription_payment_spec.rb
> +    context 'when transaction has credit_card as the payment_method with paid status' do
**Cosmético**
Aqui era pra ser o contexto quando a transação é com cartão de crédito e o status não é pago.

2021-05-20 11:39 UTC, devton approved these changes

2021-05-21 10:31 UTC, merged

2021-06-01 04:04 UTC, thiagocatarse commented
sandbox-ok

2021-06-01 10:24 UTC, thiagocatarse commented
sandbox-ok