✨ Valida usuário do pagamento é dono do cartão de crédito.
common-group/services-core pull request #895
Opened 2021-05-20 16:42 UTC by gabrielras

### Descrição
Atualmente, é possível que o pagamento seja processado com um id cartão de crédito que pertence a outro usuário. Foi criada então uma validação para esse caso.
 
### Referência
https://www.notion.so/catarse/Validar-que-usu-rio-do-pagamento-o-dono-do-cart-o-de-cr-dito-a5353d6b0452496385965d43bb1aa7ec

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-20 17:24 UTC, stephannv requested changes

2021-05-20 17:24 UTC, stephannv commented on services/catarse/config/locales/billing.en.yml
> +          invalid_user_for_credit_card: "credit card user does not match payment"
```suggestion
          invalid_credit_card: "credit card owner doesn't match user"
```

2021-05-20 17:24 UTC, stephannv commented on services/catarse/app/models/billing/payment.rb
> +      errors.add(:credit_card, I18n.t('models.billing.payment.errors.invalid_user_for_credit_card'))
```suggestion
      errors.add(:credit_card_id, I18n.t('models.billing.payment.errors.invalid_user_for_credit_card'))
```

2021-05-20 17:24 UTC, stephannv commented on services/catarse/config/locales/billing.pt.yml
> +          invalid_user_for_credit_card: "usuário do cartão de credito não corresponde ao de pagamento"
```suggestion
          invalid_user_for_credit_card: "usuário do cartão de credito não corresponde ao do pagamento"
```

2021-05-20 17:24 UTC, stephannv commented on services/catarse/spec/factories/billing/payments_factories.rb
> +      user { credit_card.user }
**Sugestão**
Melhor é o usuário do cartão de crédito usar o usuário do pagamento do que o contrário. Se ficar do jeito que tá, se eu fizer: `create(:billing_payment, :with_credit_card, user: meu_user)`, provavelmente o usuário do pagamento não ficará sendo o que eu informei na criação da factory.

2021-05-20 17:24 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +    context 'when credit card user corresponds to payment' do
```suggestion
    context 'when credit card owner matches user' do
```

2021-05-20 17:24 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +      let(:payment) { build(:billing_payment, :with_credit_card) }
**Sugestão**
User `subject` ao invés de `let` para o pagamento, pois ele é o sujeito sendo testado.
Ao invés de usar factory, tu pode usar o `Billing::Payment.new`.
Ex.:
```ruby
subject(:payment) { Billing::Payment.new(user: user, credit_card: credit_card) }

let(:user) { ... }
let(:credit_card) { ... }
```

2021-05-20 17:24 UTC, stephannv commented on services/catarse/spec/models/billing/payment_spec.rb
> +      it 'adds invalid user for credit card error message' do
```suggestion
      it 'adds invalid credit card error message' do
```

2021-05-21 12:12 UTC, gabrielras commented on services/catarse/app/models/billing/payment.rb
> +      return if user == credit_card.user
@stephannv ao comparar os **user_id == credit_card.user_id** gera um erro nos teste pq o build deixa o id nil. Então eu utilizei o create.

2021-05-21 13:04 UTC, stephannv requested changes

2021-05-21 16:40 UTC, stephannv approved these changes

2021-05-21 16:41 UTC, merged