✨ Implementa calendário com dias úteis.
common-group/services-core pull request #909
Opened 2021-05-25 15:43 UTC by gabrielras

### Descrição
Implementa calendário com dias úteis e considera os feriados.

### Referência
https://www.notion.so/catarse/Implementar-dias-teis-abf688c68a33497d8ab2abf31f82a153

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-25 16:19 UTC, stephannv requested changes

2021-05-25 16:19 UTC, stephannv commented on services/catarse/Gemfile
> +gem 'business', '~> 2.0'
**Sugestão**
Seguir o padrão das demais gems e usar uma versão fixa.

2021-05-25 16:19 UTC, stephannv commented on services/catarse/app/lib/business_calendar.rb
> +class BusinessCalendar
**Sugestão**
Ao invés de criar uma classe, cria um initializer e lá tu inicializa uma variável global:
```
BusinessCalendar = Business::Calendar.new(...)
```
Assim o objeto será carregado apenas uma vez, e quem for utilizar não precisará criar uma instância nova toda vida.

2021-05-26 14:30 UTC, stephannv requested changes

2021-05-26 14:30 UTC, stephannv commented on services/catarse/config/initializers/business_calendar.rb
> +end
**Sugestão**
Pode remover esse método, fazer isso:
```ruby
holidays = Holidays.between(...).pluck(:date)
```
Que é a mesma coisa que tu fazer:
```ruby
holidays = Holidays.between(...).map { |item| item[:date] }
```
Que é basicamente o mesmo código que tu escreveu, mas com menos linhas.

2021-05-26 14:30 UTC, stephannv commented on services/catarse/config/initializers/business_calendar.rb
> +  name: 'business calendar',
**Dúvida**
A gente pode remover esse parâmetro da inicialização, já que não iremos utilizar isso pra nada?

2021-05-26 14:30 UTC, stephannv commented on services/catarse/spec/config/initializers/business_calendar_spec.rb
> +      expect(described_class.holidays).to include(holiday_date)
**Sugestão**
Aqui tu pode fazer assim, pois é mais importante a gente verificar que o `business_day?` funcione do que testar que a lista de fériados esteja preenchida.
```ruby
expect(calendar.business_day?(holiday_date)).to be false
```

2021-05-26 14:30 UTC, stephannv commented on services/catarse/spec/config/initializers/business_calendar_spec.rb
> +    it 'returns business day' do
**Sugestão**
Melhorar descrição desse teste para dizer o que o método realmente faz. 
Além de testar com finais de semana, testar com feriados também.

2021-05-27 12:23 UTC, stephannv requested changes

2021-05-27 12:23 UTC, stephannv commented on services/catarse/app/lib/utils/business_calendar.rb
> +    end
**Sugestão**
A gente não precisa expor esse método pois não vejo a gente necessitando dele, caso algum dia apareça a necessidade, aí faremos a exposição.

2021-05-27 12:23 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +# singleton_spec.rb
**Dúvida**
Esse comentário é necessário?

2021-05-27 12:23 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +require 'singleton'
**Dúvida**
Esse `require` é necessário?

2021-05-27 12:23 UTC, stephannv commented on services/catarse/app/lib/utils/business_calendar.rb
> +require 'singleton'
**Dúvida**
Esse require é necessário?

2021-05-27 12:23 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +    end
**Sugestão**
A gente não precisa mais testar que ele é uma instância de um Business::Calendar. Agora a gente encapsulou nossa regra de negócio, nessa Utils::BusinessCalendar, e se algum momento a gente quiser trocar de gem ou fazer implementação própria, o teste deve continuar passando, independente da implementação que utilizaremos.

2021-05-27 12:23 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +  describe 'BusinessCalendar' do
**Sugestão**
Separar os testes de `#business_day?` e `#add_business_day` em seus próprios describes.

2021-05-27 12:30 UTC, gabrielras commented on services/catarse/app/lib/utils/business_calendar.rb
> +    end
@stephannv eu tbm n vi muita utilidade nesse método, mas ele me permite garantir nos testes que os dias uteis são segunda, terça, quarta e quinta. Eu excluo esse método, mas eu mantenho o teste dos dias uteis capturando do calendar?

2021-05-27 13:00 UTC, gabrielras commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +require 'singleton'
Não é, vi exemplos onde utilizavam o singleton e todos tinha require, mas quando removi continuou funcionando corretamente.

2021-05-27 13:11 UTC, stephannv commented on services/catarse/app/lib/utils/business_calendar.rb
> +    end
@gabrielras tu pode testar isso no `add_business_day`. Se tu tiver uma data que é na segunda, adicionar 4 dias úteis, a data que é pra retornar, é uma sexta feira. Isso tu garante que o comportamento é o esperado.

2021-05-27 13:14 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +    end
@gabrielras mas esse `working_days` não é algo que a gente precise sabe. Só precisamos saber duas coisas até o momento: Se uma data é dia útil, e o cálculo de dias úteis, se um dia a própria gem mudar sua api, ou a gente trocar de gem, ou usar uma implementação própria, o importante vai ser saber que uma data é dia útil e que o cálculo de dias úteis está funcionando.

2021-05-27 13:22 UTC, stephannv requested changes

2021-05-27 13:22 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +  end
**Sugestão**
Usar contextos para descrever melhor cada situação,
tipo:
```ruby
  context 'with ' do
    it 'returns true'
      ...
    end
  end

  context 'with ' do
    it 'returns true'
      ...
    end
  end

```

2021-05-27 13:22 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +      it 'returns the correct date' do
```suggestion
      it 'returns first date after weekend' do
```

2021-05-27 13:22 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +      it 'returns the correct date' do
it 'returns first date after holiday' do

2021-05-27 13:22 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +    it 'returns business day' do
**Sugestão**
Adicionar um contexto aqui também e melhorar essa descrição.

2021-05-27 14:02 UTC, stephannv requested changes

2021-05-27 14:02 UTC, stephannv commented on services/catarse/spec/lib/utils/business_calendar_spec.rb
> +      it 'returns working day' do
```suggestion
    context 'when adding business day over business days' do
      it 'returns business day without skips' do
```

2021-05-27 16:33 UTC, merged