🐞 Ajusta tratamento de erro para bad gateway ao baixar dados da pagarme.
common-group/services-core pull request #918
Opened 2021-05-28 12:31 UTC by gabrielras

### Descrição
Ao fazer a rotina de baixar dados da pagar.me, as vezes explode e para a tarefa no meio do método update_or_create_gateway_payment. Devemos tratar, esse erro quando for de RestClient::BadGateway.

### Referência
https://www.notion.so/catarse/Corrigir-Problema-de-Baixar-dados-Pagame-c2daed9b8b9343e298e80e20b863326e

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-05-28 13:09 UTC, stephannv requested changes

2021-05-28 13:09 UTC, stephannv commented on services/catarse/lib/tasks/gateway_payment_sync.rake
> +    update_or_create_gateway_payment(transaction)
**Problema**
Se por algum acaso, o erro de bad gateway for persistente, isso aqui vira um loop infinito. Mais seguro é fazer apenas algumas retentativas
```suggestion
  def ...
    retries ||= 0
    ...
  rescue RestClient::BadGateway => e
    raise e if retries > 3
    retries += 1
    sleep 3
    retry
```

2021-05-28 13:41 UTC, stephannv approved these changes

2021-06-01 13:03 UTC, leticia-fernandes approved these changes

2021-06-01 13:09 UTC, merged

2021-06-03 00:05 UTC, thiagocatarse commented
sandbox-ok