Feature/landing page coming soon
common-group/services-core pull request #921
Opened 2021-05-31 22:51 UTC by grpse

### Descrição
Página de pré-lançamento

### Referência
https://www.notion.so/catarse/Implementar-P-gina-de-Pr-lan-amento-no-Catarse-Em-breve-no-Catarse-0918f974ee6a43d5b6603e376157743f

### Antes de criar esse pull request confira se:
- [ ] Testes estão implementados
- [ ] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [ ] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [ ] Revisou seu próprio código
- [ ] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-06-07 13:19 UTC, stephannv requested changes

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/views/catarse_bootstrap/projects/coming_soon.html.slim
> +  = javascript_include_tag "jquery-ui"
**Cosmético**
Faltou a final new line aqui.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/catarse.js/legacy/src/root/projects/coming-soon-landing-page.css
> +} */
**Dúvida**
Isso será necessário em algum momento? Caso contrário, seria bom remover.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/config/routes.rb
> +          end
**Sugestão**
Pelo que entendi, a ativição e desativação do coming_soon será feita individualmente por projeto. Então imagino que o melhor pra esse caso seria que o id do projeto fosse um parâmetro de rota:
```suggestion
          member do
            post :activate
            delete :deactivate
          end
```

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/controllers/projects/integrations_controller.rb
> +  def destroy
**Problema**
Faltou o spec disso.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/controllers/projects_controller.rb
> +    if params[:permalink].present?
**Problema**
Faltou o spec desse novo funcionamento.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/models/project.rb
> +  def notify_reminder_of_publish(options = {})
**Problema**
Faltou o spec disso.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/models/project_integration.rb
> +  }
**Problema**
Faltaram os specs disso.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/observers/project_observer.rb
> +
**Problema**
Faltou o spec disso.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/app/policies/project_integration_policy.rb
> +  end
**Problema**
Faltaram os specs disso.

2021-06-07 13:19 UTC, stephannv commented on services/catarse/spec/controllers/projects/coming_soon_controller_spec.rb
> +    end
**Problema**
Aqui precisa ser testado que fez o realmente era pra fazer, como por exemplo: verificar que o rescurso foi destruído e que os reminders também foram destruídos.

2021-06-07 22:58 UTC, grpse commented on services/catarse/app/controllers/projects/coming_soon_controller.rb
> +      @integration.localized.attributes = attributes
Blz, estou removendo. Não faz nenhum sentido mesmo.

2021-06-07 22:58 UTC, grpse commented on services/catarse/app/controllers/projects_controller.rb
> +    end
Boa. Vou aplicar a tua sugestão.

2021-06-07 23:09 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +
Isso é uma feature na verdade. O projeto precisa ter 2 permalinks, um da campanha, que pode ser alterado depois e outro que é o da campanha de pré-lançamento. Esse permalink não tem uma funcionalidade de trocar ele, então está sendo gerado utilizando a base do nome do projeto e um "SecureRandom" (que é único devido ao baixíssimo risco de colisão e a integração vai ser apagada depois de o projeto ser publicado.

Realmente não tem índice, mas como a tabela de integrations é muito pequena, não deve ser problemático ainda. Daria para fazer o índice na coluna `data` para já deixar pronto isso ou colocar um índice nas colunas project_id e name, pois ali é que acontecem as seleções. Que acha?

2021-06-07 23:18 UTC, grpse commented on services/catarse/app/controllers/projects_controller.rb
> +      @coming_soon = ProjectIntegration.by_permalink(permalink).first
A página de pré-lançamento tem seu próprio permalink. Acredito que no momento não vá impactar na performance, pois a lista de integrações com pré-lançamento é muito menor do que a lista de projetos.

2021-06-07 23:19 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +    project.validates_presence_of :uploaded_image, unless: ->(project) { project.video_thumbnail.present? }
Vou aplicar

2021-06-07 23:27 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +    end
Vou aplicar. Acho que é `errors.merge!(project.errors)`

2021-06-07 23:27 UTC, grpse commented on services/catarse/app/views/catarse_bootstrap/projects/coming_soon.html.slim
> +  = javascript_include_tag "jquery-ui"
Aplicar

2021-06-07 23:28 UTC, grpse commented on services/catarse/catarse.js/legacy/src/root/projects/coming-soon-landing-page.css
> +} */
Passou sem querer. Removendo!

2021-06-07 23:30 UTC, grpse commented on services/catarse/config/routes.rb
> +          end
A rota aqui é `/projects/<project_id>/coming_soon/{activate,deactivate}`. Tu está dizendo para fazer com que ela fique `/coming_soon/<project_id>/{activate,deactivate}` ?

2021-06-07 23:32 UTC, grpse commented on services/catarse/spec/controllers/projects/coming_soon_controller_spec.rb
> +    end
Verdade, isso aqui não garante nada. Vou corrigir.

2021-06-07 23:35 UTC, grpse commented on services/catarse/app/controllers/projects/integrations_controller.rb
> +  def destroy
Esse método passou a existir, mas não é necessário para o funcionamento.

2021-06-07 23:37 UTC, grpse commented on services/catarse/app/controllers/projects/integrations_controller.rb
> +  def destroy
Removendo

2021-06-08 13:49 UTC, leticia-fernandes commented on services/catarse/app/controllers/projects/coming_soon_controller.rb
> +    def permitted_params
Essa função tá sendo utilizada?

2021-06-08 13:51 UTC, leticia-fernandes commented on services/catarse/app/controllers/projects/integrations_controller.rb
> -
Tem algum motivo específico para o `private` ser removido?

2021-06-09 16:45 UTC, stephannv commented on services/catarse/app/models/project_integration.rb
> +
@grpse seria bom o index nesses dois campos, pelo que vi uma consulta é feita no `name` e no `data->>'url'` e a outra é o `project_id`. O @devton pode nos ajudar aqui nesse ponto.

2021-06-09 18:43 UTC, stephannv commented on services/catarse/app/models/project_integration.rb
> +    end
@grpse tem certeza que o jeito que tu colocou funciona?
Olhei nas documentação e vi que internamente ele já faz o `.errors` no objeto que tu passou como parâmetro.

<img width="403" alt="Screen Shot 2021-06-09 at 3 40 52 PM" src="https://user-images.githubusercontent.com/3025661/121410657-30901580-c939-11eb-9cf5-89a4d6a553e1.png">

https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-merge-21

2021-06-09 18:50 UTC, stephannv commented on services/catarse/config/routes.rb
> +          end
Verdade @grpse , tá certo, é que não percebi que era dentro do coming-soon esse código.
Só uma dica, tu pode fazer só isso aqui, ao invés do `resources :coming_soon...,`  já que coming_soon não é um recurso:
```ruby
resource :projects, ... do
   ...
   member do
     post 'coming-soon/activate', to: 'projects/coming_soon#activate'
     delete 'coming-soon/deactivate', to: 'projects/coming_soon#deactivate'
   end
end
```

2021-06-09 18:57 UTC, devton commented on services/catarse/app/models/project_integration.rb
> +
isso o indice no project_id acho o rails ali ja ate coloca junto com a chave estrangeira, agora esse indice no data->>'url' a gente pode fazer ```CREATE UNIQUE INDEX ON project_integrations((data->>'url'));``` o unique ai seria legal pra gente ja garantir que não vai existir outra integração com utilizando o msm permalink, se colocar um where ali a gente pode excluir a unicidade das integrações que não forem ativas

2021-06-09 19:20 UTC, stephannv commented on services/catarse/app/models/project_integration.rb
> +
@devton olhei no banco de produção e não vi index nessa coluna. Talvez o Rails antigo não gerasse automáticamente esse index quando fazia um belongs_to na migration.

2021-06-10 12:14 UTC, grpse commented on services/catarse/config/routes.rb
> +          end
@stephannv eu tentei desse modo, mas não funcionou.

2021-06-10 22:33 UTC, grpse commented on services/catarse/app/controllers/projects/integrations_controller.rb
> -
Não tem não. Viajei aqui.

2021-06-10 22:34 UTC, grpse commented on services/catarse/app/controllers/projects/coming_soon_controller.rb
> +    def permitted_params
não tá não. removendo...

2021-06-10 22:35 UTC, grpse commented on services/catarse/spec/controllers/projects/coming_soon_controller_spec.rb
> +    end
Adicionando

2021-06-10 22:48 UTC, grpse commented on services/catarse/app/policies/project_integration_policy.rb
> +  end
Adicionando

2021-06-10 22:54 UTC, grpse commented on services/catarse/app/observers/project_observer.rb
> +
adicionando

2021-06-11 12:18 UTC, grpse commented on services/catarse/app/models/project.rb
> +  def notify_reminder_of_publish(options = {})
adicionei o teste https://github.com/common-group/services-core/pull/921/files#diff-20898fe99f2ba46b95ee4a5c30771892aefd5d1e46360a576c54fc83e6a289bbR6

2021-06-11 12:18 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +    end
ajustado

2021-06-11 12:20 UTC, grpse commented on services/catarse/app/controllers/projects_controller.rb
> +      @coming_soon = ProjectIntegration.by_permalink(permalink).first
Mudei a forma conforme discutimos antes. Agora se o pré-lançamento estiver ativo, vai buscar primeiro pelo permalink e retorna para a página de pré-lançamento, caso seja o que eu estou chamando de draft_url carrega a página de rascunho do projeto.

2021-06-12 00:52 UTC, grpse commented on services/catarse/config/routes.rb
> +          end
Os parâmetros que estavam sendo pegos na url dos testes eram `:project_id` e agora devem ser `:id` somente já que declarei como membro. Já ajustei.

2021-06-12 00:52 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +  }
adicionados

2021-06-12 00:58 UTC, grpse commented on services/catarse/app/controllers/projects_controller.rb
> +    if params[:permalink].present?
coloquei um spec simples pq caso o projeto não seja encontrado com o permalink ele retorna 404.

2021-06-12 01:10 UTC, grpse commented on services/catarse/app/models/project_integration.rb
> +
feito

2021-06-14 16:22 UTC, stephannv approved these changes

2021-06-15 20:07 UTC, devton requested changes

2021-06-15 20:07 UTC, devton commented on services/catarse/db/migrate/20210612005925_add_index_to_project_integration_name_and_data.rb
> +    CREATE UNIQUE INDEX project_integrations_idx_name ON project_integrations(name);
@grpse esse indice aqui precisa ser composto com o id do projeto, project_integrations(project_id, name). O nome ali vai se repetir para outros projetos certo?

2021-06-22 01:25 UTC, grpse commented on services/catarse/db/migrate/20210612005925_add_index_to_project_integration_name_and_data.rb
> +    CREATE UNIQUE INDEX project_integrations_idx_name ON project_integrations(name);
@devton coloquei o name, project_id e data->>'draft_url'

2021-06-22 20:07 UTC, devton approved these changes

2021-06-22 20:07 UTC, merged