✨ Valida estimativa de entrega de recompensas ao publicar o projeto
common-group/services-core pull request #944
Opened 2021-06-15 18:15 UTC by gabrielras

### Descrição
Projeto criado a mais tempo conseguem criar recompensas com data de entrega no passado.

### Referência
https://www.notion.so/catarse/Validar-estimativa-de-entrega-de-recompensas-ao-publicar-o-projeto-4af8905f6dc449a2a446cb77dfaf8392

### Antes de criar esse pull request confira se:
- [x] Testes estão implementados
- [x] Descreveu bem o título do PR a mensagem de commit e usou o emoji no início da mensagem.
- [x] Mudanças estão unificadas em um único commit e só há 1 commit no pull request.
- [x] Revisou seu próprio código
- [x] Adicionou o link desse pull request no card da atividade
- [ ] A base de conhecimento foi atualizada (Isso para quando tivermos uma)

2021-06-15 20:11 UTC, devton requested changes

2021-06-15 20:11 UTC, devton commented on services/catarse/app/models/project.rb
> +    if self.online? && rewards.present? && rewards.select{ |r| r.deliver_at < DateTime.now.beginning_of_day }.present?
@gabrielras aqui o rewards.select vai carregar todas as recompensas na memoria se não me engano. O ideal seria fazer um rewards.where(deliver_date: ..DateTime.now.begining_of_day)

@stephannv me confirma aqui dps se é ..Date... ou Date.. nunca lembro a ordem ali dos ..

2021-06-15 22:26 UTC, stephannv requested changes

2021-06-15 22:26 UTC, stephannv commented on services/catarse/app/models/project.rb
> +  validate :rewards_have_correct_deliver_at_for_online_project
**Sugestão**
Mover essa validação para o Project::BaseValidator pois lá tem algumas validações customizadas de acordo com o estado do projeto.

Tambem sugiro utilizar esse termo:
```suggestion
  validate :rewards_deliver_date_cannot_be_in_the_past
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/app/models/project.rb
> +    if self.online? && rewards.present? && rewards.select{ |r| r.deliver_at < DateTime.now.beginning_of_day }.present?
Esse`online?` tu consegue mover para uma condição da validação, ex.: `validate :foo, if: :online?`.  E como o Ton falou, dessa forma que tu fez, tu tá buscando todo mundo no select, iterando como um array e filtrando no ruby, mas como é uma relação has many, tu consegue já fazer tudo no SQL assim:
```suggestion
    if rewards.exists?(deliver_at: ..Time.zone.now)
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/app/models/project.rb
> +      errors.add(:reward, I18n.t('activerecord.errors.models.project.attributes.rewards.deliver_at_invalid'))
**Sugestão**
Talvez fazendo só assim funcione:
```suggestion
      errors.add(:reward, :deliver_at_in_the_past)
```
Caso não, acho que com algum ajuste no local onde foi definida a mensagem, tu consegue fazer funcionar sem precisar passar o path inteiro.

2021-06-15 22:26 UTC, stephannv commented on services/catarse/config/locales/catarse_bootstrap/activerecord.en.yml
> +              deliver_at_invalid: Invalid delivery date
```suggestion
              deliver_at_in_the_past: Delivery date cannot be in the past
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/config/locales/catarse_bootstrap/activerecord.pt.yml
> +              deliver_at_invalid: 'Data de entrega inválida'
```suggestion
              deliver_at_in_the_past: Data de entrega não pode ser anterior à hoje.
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/spec/models/project_spec.rb
> +    context 'when an online project has rewards with correct delivery date' do
**Sugestão**
Usar `a data de entrega correta` ou `a data de entrega inválida` não ajuda a saber o que é correto ou o que é inválido, nessa situação fica mais claro especificar `data de entrega no futuro` e `data de entrega no passado` e quem ler já vai saber o que leva o objeto ser válido ou não.
```suggestion
    context 'when an online project has rewards with delivery date in the future' do
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/spec/models/project_spec.rb
> +      it 'doesn`t add invalid reward error' do
```suggestion
      it 'doesn`t add deliver_at_in_the_past error' do
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/spec/models/project_spec.rb
> +    context 'when an online project has rewards with incorrect delivery date' do
```suggestion
    context 'when an online project has rewards with delivery date in the past' do
```

2021-06-15 22:26 UTC, stephannv commented on services/catarse/spec/models/project_spec.rb
> +      it 'adds invalid invalid reward error message' do
```suggestion
      it 'adds deliver_at_in_the_past error message' do
```

2021-06-16 17:45 UTC, gabrielras commented on services/catarse/app/models/project.rb
> +    if self.online? && rewards.present? && rewards.select{ |r| r.deliver_at < DateTime.now.beginning_of_day }.present?
@devton, vi aqui com o @stephannv e no validate o reward ainda não está persistido, então quando se usa o where ou existis ele retorna false por isso ainda mantive o select.

2021-06-16 22:22 UTC, devton approved these changes

2021-06-17 11:54 UTC, stephannv requested changes

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/concerns/project/base_validator.rb
> +
**Problema**
Essa validação tá dentro do bloco que executa quando o projeto muda o estado para algum desses: `online` `successful` `waiting_funds` `failed`. A validação deve ser feita apenas quando o projeto estiver sendo publicado, caso contrário pode acabar impedindo que um projeto mude pra outro estado (caso o `expires_at` que estava no futuro quando o projeto foi ao ar, mas que no momento de encerrar o projeto esse `expires_at` esteja no passado, daí tua validação impediria essa troca de estado.)

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/reward.rb
> +  validate :rewards_deliver_date_cannot_be_in_the_past, if: :deliver_at?
**Sugestão**
Como isso já está dentro da classe Reward, não precisa desse prefixo `rewards_...`.
```suggestion
  validate :deliver_date_cannot_be_in_the_past, if: :deliver_at?
```

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/reward.rb
> +  def rewards_deliver_date_cannot_be_in_the_past
```suggestion
  def deliver_date_cannot_be_in_the_past
```

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/reward.rb
> +      errors.add(:deliver_at, I18n.t('activerecord.errors.models.reward.attributes.deliver_at_in_the_past'))
**Dúvida**
Aqui tu não consegue utilizar apenas `:deliver_at_in_the_past`? Igual como tu fez na validação do Project, ao invés de usar o path inteiro.

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/concerns/project/base_validator.rb
> +        if project.rewards.present? && project.rewards.select{ |r| r.deliver_at < DateTime.now.beginning_of_day }.present?
**Sugestão**
Usar `Time.zone.today` para esse caso e `Time.zone.now` quando necessitar pegar o horário do momento em alguma atividade futura.

2021-06-17 11:54 UTC, stephannv commented on services/catarse/app/models/reward.rb
> +    if deliver_at < DateTime.now.beginning_of_day
```suggestion
    if deliver_at < Time.zone.today
```

2021-06-17 11:54 UTC, stephannv commented on services/catarse/config/locales/catarse_bootstrap/activerecord.en.yml
> +            deliver_at_in_the_past: Delivery date cannot be in the past
**Sugestão**
Tu criando uma estrutura no yml dessa forma, tu consegue aproveitar a mesma mensagem pra vários modelos:
```yml
 activerecord:
    errors:
      messages:
        common_error: 'is common'
 ```

2021-06-17 11:54 UTC, stephannv commented on services/catarse/spec/models/reward_spec.rb
> +    context 'when saved rewards with delivery date in the future' do
```suggestion
    context 'when deliver_at is in the future' do
```

2021-06-17 11:54 UTC, stephannv commented on services/catarse/spec/models/reward_spec.rb
> +    context 'when saved rewards with delivery date in the past' do
```suggestion
    context 'when deliver_at is in the past' do
```

2021-06-18 19:57 UTC, stephannv requested changes

2021-06-18 19:57 UTC, stephannv commented on services/catarse/app/models/concerns/project/base_validator.rb
> +
**Problema**
Essa validação ainda tá dentro do bloco que executa quando o projeto muda o estado para algum desses: online successful waiting_funds failed. A validação deve ser feita apenas quando o projeto estiver sendo publicado pelos motivos que expliquei no code review anterior. Um pouco mais acima dessa classe tem o bloco: `with_options if: :online? do |wo|` que é executado apenas quando o projeto está sendo publicado.

2021-06-18 19:57 UTC, stephannv commented on services/catarse/app/models/concerns/project/base_validator.rb
> +          errors.add(:rewards, I18n.t('activerecord.errors.messages.deliver_at_in_the_past'))
**Dúvida**
O `errors.add(:rewards, :deliver_at_in_the_past)` não funciona?

2021-06-21 01:56 UTC, gabrielras commented on services/catarse/app/models/concerns/project/base_validator.rb
> +          errors.add(:rewards, I18n.t('activerecord.errors.messages.deliver_at_in_the_past'))
Oi stephann, sobre essa mudança deu certo sim, fiz o ajuste e adicionei.

2021-06-21 01:57 UTC, gabrielras commented on services/catarse/app/models/concerns/project/base_validator.rb
> +
Vdd, eu tinha adicionado apenas um project.online?, mas já existe uma validação específica lá. Então adicionei a nova alteração.

2021-06-23 17:19 UTC, stephannv approved these changes

2021-07-01 12:09 UTC, leticia-fernandes approved these changes

2021-07-05 18:19 UTC, stephannv commented
@devton depois revisa esse PR aqui, por favor.

2021-07-06 11:48 UTC, devton approved these changes

2021-07-06 12:13 UTC, merged